# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

# pod 'AFNetworking', '~> 3.0'
# pod 'OpenSSL-for-iOS', '1.0.2.d.1'

pod 'AWSPolly'
pod 'AWSRekognition'
pod 'AWSS3'

target 'demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for demo

end
